general.import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

general.live_config_reload = true

[env]
term = "xterm-256color"
PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
TERM = "alacritty-direct"

[window]
decorations = "full"
opacity = 1
blur = true
option_as_alt = "Both"
startup_mode = "Maximized"

[font]
normal.family = "Hack Nerd Font Mono"
normal.style = "Regular"
bold.family = "Hack Nerd Font Propo"
bold.style = "Bold"
italic.family = "Hack Nerd Font"
italic.style = "Italic"
bold_italic.family = "Hack Nerd Font"
bold_italic.style = "Bold Italic"
size = 19
offset = { y = 2 }

[terminal.shell]
program = "tmux"
args = ["new-session", "-A", "-s", "main", "zsh"]

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]

[selection]
save_to_clipboard = true
