return {
  -- disable trouble
  { "MagicDuck/grug-far.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "echasnovski/mini.move", enabled = false },
  { "echasnovski/mini.hipatterns", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "folke/ts-comments.nvim", enabled = false },
  { "nvim-neotest/neotest", enabled = false },
  { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
  { "monaqa/dial.nvim", enabled = false },
  { "smjonas/inc-rename.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "gbprod/yanky.nvim", enabled = false },
}
