vim.cmd("set clipboard=unnamed")
vim.cmd("set signcolumn=yes")
vim.cmd("set noswapfile")
vim.cmd("set colorcolumn=80")
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
vim.cmd("set shell=/bin/zsh")
vim.cmd("setlocal spell spelllang=en_us")
